/**
* AI Progress Tracker Frontend Configuration
*
* Auto-generated from backend .env files on 2025-07-12 22:18:07
* DO NOT EDIT THIS FILE MANUALLY - your changes will be overwritten!
*
* To update configuration:
* 1. Edit the appropriate .env file (.env.prod, .env.stg, .env)
* 2. Run: python scripts/build-frontend-config.py
* 3. Redeploy your frontend
*/
        
const config = {
  "development": {
    "API_URL": "http://localhost:8000",
    "DEBUG": true,
    "ENVIRONMENT": "development",
    "ANALYTICS_ENABLED": true,
    "SPACED_REPETITION_ENABLED": true,
    "DEFAULT_XP_MULTIPLIER": 1.0
  },
  "production": {
    "API_URL": "",
    "DEBUG": false,
    "ENVIRONMENT": "production",
    "ANALYTICS_ENABLED": true,
    "SPACED_REPETITION_ENABLED": true,
    "DEFAULT_XP_MULTIPLIER": 1.0
  },
  "staging": {
    "API_URL": "",
    "DEBUG": true,
    "ENVIRONMENT": "staging",
    "ANALYTICS_ENABLED": true,
    "SPACED_REPETITION_ENABLED": true,
    "DEFAULT_XP_MULTIPLIER": 1.0
  }
};

/**
* Environment Detection
*/
function detectEnvironment() {
    const hostname = window.location.hostname;
    
    if (hostname === 'localhost' || hostname === '127.0.0.1') {
        return 'development';
    }
    
    if (hostname.includes('staging')) {
        return 'staging';
    }
    
    return 'production';
}

// Get current environment configuration
const currentEnvironment = detectEnvironment();
const currentConfig = config[currentEnvironment];

if (!currentConfig) {
    console.error(`No configuration found for environment: ${currentEnvironment}`);
    window.AITrackerConfig = config.development || {};
} else {
    window.AITrackerConfig = currentConfig;
}

window.AITrackerConfig.DETECTED_ENVIRONMENT = currentEnvironment;

// Debug logging
if (currentConfig && currentConfig.DEBUG) {
    console.log('🎯 AI Tracker Configuration Loaded');
    console.log('Environment:', currentEnvironment);
    console.log('API URL:', currentConfig.API_URL);
    console.log('Full Config:', currentConfig);
}

// Export for modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { config, currentConfig: window.AITrackerConfig };
}
